apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 2
  selector:
    app: guestbook
    tier: frontend
  template:
      metadata:
        labels:
          app: guestbook
          tier: frontend
      spec:
        containers:
          - name: unitrans-front
            image: eu.gcr.io/unitrans-1107/unitrans_image
            resources:
              requests:
                cpu: 20m
                memory: 100Mi
            env:
              - name: REDIS_ADDR
                value: redis-master:6379
            ports:
            - containerPort: 8088